apiVersion: v1 
kind: Service 
metadata:   
 name: fractals-service 
 labels:
  app: fractals
spec:   
 selector: 	
  app: fractals   
 type: NodePort  
 ports:   
 - port: 8080
   targetPort: 8080
   nodePort: 32001 	
 

